version: "3.7"

services:
# ---------------------------------------- MariaDB
  mariadb:
    container_name: mariadb
    image: mariadb
    build: requirements/mariadb/.
    networks:
      - inception
    restart: always
    volumes:
      - database:/var/lib/mysql
    env_file:
      - ./.env
# ---------------------------------------- Wordpress
  wordpress:
    container_name: wordpress
    image: wordpress
    build: requirements/wordpress/.
    networks:
      inception:
    restart: always
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - mariadb
    env_file:
      - ./.env
# ---------------------------------------- Nginx
  nginx:
    container_name: nginx
    image: nginx
    build: 
      context: requirements/nginx/.
    networks:
      inception:
    restart: always
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - wordpress
    env_file:
      - ./.env

# ---------------------------------------- network
networks:
  inception:
# ---------------------------------------- volumes
volumes:
  database:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/cpopa/data/mariadb # mount host directory for MariaDB data
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/cpopa/data/wordpress # mount host directory for Wordpress data
